name: Guardian Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 4 * * *' # Dagelijkse scan om 04:00 UTC

permissions:
  contents: read

jobs:
  lint-format-audit:
    runs-on: ubuntu-latest
    name: Lint, Format & Security Audit

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run npm audit
        run: npm audit --audit-level=moderate || true
