name: Security Scan (njsscan + Secrets Check)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '34 3 * * *' 

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run njsscan on codebase
        id: njsscan
        uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload njsscan report to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Search for hardcoded secrets or passwords
        run: |
          echo "Scanning for hardcoded passwords or secrets..."
          FOUND=$(grep -r -iE 'password\s*[:=]|pwd\s*[:=]|secret\s*[:=]|API[_-]?KEY\s*[:=]' . --exclude-dir={.git,node_modules} || true)
          if [[ ! -z "$FOUND" ]]; then
            echo "::warning::Possible hardcoded secrets found:"
            echo "$FOUND"
            exit 1
          else
            echo "✅ No obvious hardcoded secrets found."
          fi
